image: node:latest

cache:
  paths:
    - node_modules/

test_lint_and_format:
  tags:
    - docker
  script:
    - npm install
    - npm run format:check
    - npm run lint
    - npm audit

test_unit:
  tags:
    - docker
  script:
    - npm install
    - npm run unit

test_integration:
  tags:
    - docker
  script:
    - npm install
    - npm run integration

build_and_package:
  tags:
    - docker
  script:
    - npm install
    - npm run build
    - npm run containerize
