image: node:latest

cache:
  paths:
    - node_modules/

test_lint_and_format:
  script:
    - npm run fmt
    - npm run lint

test_unit:
  script:
    - npm install
    - npm run unit

test_integration:
  script:
    - npm install
    - npm run integration

build_and_package:
  script:
    - npm install
    - npm run build
    - npm run package
